from pushdown_auto import balanced_parens_pda, anbn_pda
bp = balanced_parens_pda()
assert bp.accepts("()")
assert bp.accepts("(())")
assert bp.accepts("()()")
assert bp.accepts("")
assert not bp.accepts("(")
assert not bp.accepts(")(")
ab = anbn_pda()
assert ab.accepts("ab")
assert ab.accepts("aabb")
assert ab.accepts("aaabbb")
assert not ab.accepts("aab")
assert not ab.accepts("a")
print("pushdown_auto tests passed")
